services:
  postgres:
    image: postgres:17
    container_name: erupsi-postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - erupsi-erp-network

  auth-service:
    build:
      context: .
      dockerfile: src/backend/auth-service/Dockerfile
    container_name: erupsi-auth-service
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      - erupsi-erp-network

  user-service:
    build:
      context: .
      dockerfile: src/backend/user-service/Dockerfile
    container_name: erupsi-user-service
    restart: unless-stopped
    ports:
      - "3002:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      - erupsi-erp-network

  ecommerce-service:
    build:
      context: .
      dockerfile: src/backend/ecommerce-service/Dockerfile
    container_name: erupsi-ecommerce-service
    restart: unless-stopped
    ports:
      - "3003:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      - erupsi-erp-network

volumes:
  postgres_data:
    external: true
    name: pgdata

networks:
  erupsi-erp-network:
    driver: bridge
